# ----------- CONFIGURABLE START -----------
title:            "apirobot"
description:      "Блог о веб-разработке"
url:              http://apirobot.me # Site url, without a slash at the end.
signoff:          "apirobot" # Your name
facebook_appid:   1808092242854200 # APP ID for like button
vk_appid:         6106125 # # APP ID for like button
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            true # Turn on twitter and facebook share buttons

links:
  - name:         Записи
    url:          /
    external:     false
  - name:         О себе
    url:          /about
    external:     false

disqus:
  shortname: apirobot # enter this from your disqus account

# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
